import Nav from '../../components/Nav'
import LineBackdrop from '../../components/LineBackdrop'

const tiers = [
  { tag: 'Preview', title: 'Free', price: '£0', desc: 'See the product direction and delayed public previews.', items: ['Delayed dashboard preview', 'Short API preview endpoints', 'Risk warnings and methodology notes', 'No credit card required'], cta: 'Coming soon', featured: false },
  { tag: 'Most popular', title: 'Dashboard Pro', price: '£49', unit: '/month', desc: 'Live smart-wallet dashboard for understanding market positioning quickly.', items: ['Live dashboard access', 'Top 50 Copycat-ranked wallet cohort', 'Asset signal board and buyer/seller pressure', 'Portfolio allocation and Copycat Index', 'Market intelligence updates'], cta: 'Start Pro', featured: true },
  { tag: 'Alerts', title: 'Dashboard + Telegram', price: '£99', unit: '/month', desc: 'Dashboard plus 15-minute movement digests and important-positioning alerts.', items: ['Everything in Dashboard Pro', '15-minute Telegram digests', 'Major conviction change alerts', 'Large accumulation/distribution alerts', 'Priority alert channels later'], cta: 'Start alerts', featured: false },
  { tag: 'API', title: 'API Developer', price: '£249', unit: '/month', desc: 'Programmatic wallet intelligence for builders, funds, and research workflows.', items: ['API key access', 'Leaderboard, wallet, fills, signals, and flow endpoints', 'Usage logging and rate limits', 'Coverage and freshness metadata', 'Commercial terms required for resale'], cta: 'Request API', featured: false },
]

export default function Pricing() {
  return <><Nav/><main className="page-shell pricing-shell"><LineBackdrop variant="pricing"/><section className="pricing-head"><p className="eyebrow">Dashboard + API</p><h1>Pricing</h1><p>Start with live Hyperliquid wallet intelligence, then add alerts or API access when you need automation.</p></section><section className="pricing-cards pricing-cards-four">{tiers.map(t => <article key={t.title} className={`plan-card ${t.featured ? 'featured' : ''}`}><span className={`plan-tag ${t.featured ? 'hot' : 'muted'}`}>{t.featured ? '★ ' : ''}{t.tag}</span><h2>{t.title}</h2><div className="plan-price">{t.price}<small>{t.unit || ''}</small></div><i className="price-accent"/><p>{t.desc}</p><ul>{t.items.map(item => <li key={item}>{item}</li>)}</ul><a className={t.featured ? 'primary-btn full' : 'outline-btn full'} href={t.title.includes('API') ? 'mailto:paulmurrin13@gmail.com?subject=Copycat%20API%20access' : '/login'}>{t.cta} <span>→</span></a></article>)}</section><div className="plan-notes"><span>♢ Stripe subscriptions and customer portal are the next launch step.</span><span>♢ API access depends on fair-use limits and data coverage.</span></div><p className="risk-bar amber-risk"><i>♢</i><span>The dashboard and API are research and market-intelligence software. They do not provide personalized financial advice. Crypto trading can result in loss.</span></p></main></>
}
