"use client"

import { useEffect, useMemo, useState } from 'react'
import Nav from '../../components/Nav'
import LineBackdrop from '../../components/LineBackdrop'
import { apiGet } from '../../lib/api'

type Status = Record<string, any>

function compact(n: any) {
  const value = Number(n || 0)
  return value.toLocaleString(undefined, { maximumFractionDigits: 0 })
}
function money(n: any) {
  const value = Number(n || 0)
  if (!Number.isFinite(value)) return '$0'
  if (Math.abs(value) >= 1_000_000_000) return `$${(value / 1_000_000_000).toFixed(1)}b`
  if (Math.abs(value) >= 1_000_000) return `$${(value / 1_000_000).toFixed(1)}m`
  if (Math.abs(value) >= 1_000) return `$${(value / 1_000).toFixed(1)}k`
  return `$${value.toFixed(0)}`
}
function freshness(ts: any) {
  const n = Number(ts || 0)
  if (!n) return 'Awaiting first sync'
  const mins = Math.max(0, Math.round((Date.now() - n) / 60000))
  if (mins < 1) return 'Updated just now'
  if (mins < 60) return `Updated ${mins}m ago`
  return `Updated ${Math.round(mins / 60)}h ago`
}
function rowWallet(r: any) {
  return r?.wallet_label || r?.short_wallet || r?.label || (r?.wallet ? `${String(r.wallet).slice(0, 6)}…${String(r.wallet).slice(-4)}` : 'Wallet')
}
function snapshotBase() {
  const configured = (process.env.NEXT_PUBLIC_SNAPSHOT_BASE_URL || '').replace(/\/+$/, '')
  if (configured) return configured
  if (typeof window !== 'undefined') return `${window.location.origin}/copycat-data`
  return '/copycat-data'
}

export default function ApiAccessPage() {
  const [status, setStatus] = useState<Status>({})
  const [leaderboard, setLeaderboard] = useState<any[]>([])
  const [tokens, setTokens] = useState<any[]>([])
  const [coverage, setCoverage] = useState<any>({})
  const [baseUrl, setBaseUrl] = useState('/copycat-data')

  useEffect(() => {
    let cancelled = false
    setBaseUrl(snapshotBase())
    async function load() {
      try {
        const [s, l, t, c] = await Promise.all([
          apiGet('/api/data/v1/status').catch(() => ({})),
          apiGet('/api/data/v1/public/leaderboard-preview?limit=8').catch(() => ({})),
          apiGet('/api/data/v1/public/token-screener-preview?limit=8').catch(() => ({})),
          apiGet('/api/data/v1/public/coverage-preview').catch(() => ({})),
        ])
        if (!cancelled) {
          setStatus(s || {})
          setLeaderboard(l?.rows || l?.data || [])
          setTokens(t?.rows || t?.data || [])
          setCoverage(c || {})
        }
      } catch {}
    }
    load()
    const id = window.setInterval(load, 60000)
    return () => { cancelled = true; window.clearInterval(id) }
  }, [])

  const scanned = Number(status.scanner_candidate_wallets_scored ?? coverage.scanner_candidate_wallets_scored ?? coverage.candidate_wallets_scored ?? 0)
  const discovered = Number(status.wallets_discovered_from_recent_trades ?? coverage.wallets_discovered_from_recent_trades ?? 0)
  const selected = Number(status.selected_wallet_count ?? coverage.selected_wallet_count ?? status.tracked_active_wallets ?? 0)
  const tracked = Number(status.tracked_active_wallets ?? coverage.wallets_fetched ?? selected ?? 0)
  const assets = Number(status.assets_with_signals ?? coverage.assets_with_signals ?? 0)
  const records = Number(coverage.recent_orders || status.recent_orders || 0)
  const claim = useMemo(() => `Free mode is serving public snapshot JSON from Cloudflare R2. ${compact(scanned)} candidate wallets scored by the local scanner; ${compact(tracked)} are currently tracked in the live dashboard.`, [scanned, tracked])

  return <><Nav/><main className="cc-dashboard-shell cc-api-customer-page"><LineBackdrop variant="dashboard" />
    <section className="cc-api-customer-hero cc-card">
      <div>
        <p className="eyebrow live">Copycat Data API</p>
        <h1>Snapshot API preview, running without Render or Supabase.</h1>
        <p>Public customer previews are now powered by compact Cloudflare R2 JSON files generated by the local Hyperliquid scanner and publisher.</p>
        <div className="action-row"><a className="primary-btn" href="/dashboard">Open dashboard <span>→</span></a><a className="outline-btn" href="/performance">View index</a></div>
      </div>
      <aside>
        <span>Free-mode data delivery</span>
        <b>Cloudflare R2 snapshots</b>
        <em>{freshness(status.updated_at_ms || coverage.updated_at_ms)}</em>
      </aside>
    </section>

    <section className="cc-api-kpi-row">
      <article className="cc-card"><small>Scanner universe</small><b>{compact(scanned)}</b><span>{discovered ? `${compact(discovered)} discovered from recent trades` : 'local candidate pool'}</span></article>
      <article className="cc-card"><small>Tracked wallets</small><b>{compact(tracked)}</b><span>{selected ? `${compact(selected)} selected by scanner` : 'publisher wallet list'}</span></article>
      <article className="cc-card"><small>Assets with signals</small><b>{compact(assets)}</b><span>from tracked live wallet state</span></article>
      <article className="cc-card"><small>Recent order rows</small><b>{compact(records)}</b><span>published as read-only snapshots</span></article>
    </section>

    <p className="cc-api-claim-note"><i>♢</i>{claim} This is market intelligence only, not financial advice. It is not yet a verified all-Hyperliquid top-50 profit claim.</p>

    <section className="cc-api-product-row">
      <article className="cc-card"><i className="feature-icon users"/><h3>Wallet rankings</h3><p>Scanner-ranked wallets using visible live wallet state, account size, exposure, activity, and current position quality.</p></article>
      <article className="cc-card"><i className="feature-icon signal"/><h3>Asset signals</h3><p>Value-weighted long/short conviction by market, including exposure, confidence, wallet participation, and tilt.</p></article>
      <article className="cc-card"><i className="feature-icon flow"/><h3>Recent flow</h3><p>Buyer/seller pressure and recent tracked-wallet order activity from the publisher snapshot.</p></article>
      <article className="cc-card"><i className="feature-icon clock"/><h3>Historical depth</h3><p>Paused in strict free mode. The public site shows current/live-ish snapshots, not a database-backed history explorer.</p></article>
    </section>

    <section className="cc-api-preview-grid">
      <article className="cc-card cc-api-preview-card">
        <div className="cc-panel-title"><h3>Leaderboard preview</h3><span>scanner-ranked sample</span></div>
        <div className="cc-scroll-table"><table><thead><tr><th>#</th><th>Wallet</th><th>Score</th><th>Account value</th><th>Open exposure</th></tr></thead><tbody>{leaderboard.slice(0, 8).map((r:any, i:number) => <tr key={r.wallet || i}><td>{r.rank || i + 1}</td><td>{rowWallet(r)}</td><td>{Number(r.copycat_score || r.score || 0).toFixed(1)}</td><td>{money(r.account_value_usd)}</td><td>{money(r.open_position_value_usd)}</td></tr>)}</tbody></table></div>
      </article>
      <article className="cc-card cc-api-preview-card">
        <div className="cc-panel-title"><h3>Asset signal preview</h3><span>top conviction</span></div>
        <div className="cc-scroll-table"><table><thead><tr><th>Asset</th><th>Tilt</th><th>Conviction</th><th>Exposure</th></tr></thead><tbody>{tokens.slice(0, 8).map((r:any, i:number) => <tr key={r.coin || i}><td>{r.coin}</td><td className={String(r.tilt || r.direction || r.signal_label).toLowerCase().includes('short') ? 'negative' : 'positive'}>{r.tilt || r.direction || r.signal_label || '—'}</td><td>{Number(r.conviction_pct || Math.abs(Number(r.signal || 0)) * 100 || 0).toFixed(0)}%</td><td>{money(r.gross_exposure_usd || r.gross_value_usd)}</td></tr>)}</tbody></table></div>
      </article>
    </section>

    <section className="cc-card cc-api-endpoint-card">
      <div><p className="eyebrow live">Developer preview</p><h2>Free-mode endpoints</h2><p>With Render suspended, these are public read-only snapshot files. Paid/private API keys need a backend later.</p></div>
      <div className="cc-api-endpoint-list">
        <code>GET {baseUrl}/dashboard-feed.json</code>
        <code>GET {baseUrl}/performance-index.json</code>
        <code>GET {baseUrl}/api/leaderboard-preview.json</code>
        <code>GET {baseUrl}/api/token-screener-preview.json</code>
        <code>GET {baseUrl}/api/coverage-preview.json</code>
        <code>GET {baseUrl}/api/ranking-audit.json</code>
      </div>
    </section>

    <footer className="cc-warning-banner"><span className="cc-shield" aria-hidden>♢</span><div className="cc-footer-main"><strong>Free-mode site parity.</strong><em>Public pages use R2 snapshots. Login, private API keys, and historical database queries remain disabled while Render/Supabase are suspended.</em></div></footer>
  </main></>
}
