import Link from 'next/link'
import Nav from '../components/Nav'
import LineBackdrop from '../components/LineBackdrop'

function SparkPreview() {
  return <svg viewBox="0 0 460 140" className="hero-chart" aria-hidden="true"><defs><linearGradient id="heroLineFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="rgba(35,233,157,.35)"/><stop offset="100%" stopColor="rgba(35,233,157,0)"/></linearGradient></defs><path className="hero-fill" d="M16 114 L78 90 L126 96 L188 55 L236 88 L300 42 L372 55 L444 30 L444 124 L16 124 Z"/><path className="hero-line" d="M16 114 L78 90 L126 96 L188 55 L236 88 L300 42 L372 55 L444 30"/><circle cx="444" cy="30" r="9"/><text x="418" y="20">7D</text></svg>
}

export default function Home() {
  return <><Nav/><main className="page-shell landing-shell"><LineBackdrop variant="landing"/><section className="landing-hero"><div className="hero-copy-block"><p className="eyebrow">Hyperliquid smart-wallet intelligence</p><h1>Track the wallets<br/>worth copying —<br/>before the crowd<br/><em>catches up.</em></h1><p className="hero-text">Copycat turns profitable-wallet positioning into clear long/short signals, value-weighted exposure, and real-time buyer/seller pressure.</p><div className="action-row"><Link className="primary-btn" href="/dashboard">Open live dashboard <span>→</span></Link><Link className="outline-btn" href="/pricing">View pricing</Link></div><div className="landing-stats"><div><i className="round-icon users"/><b>50</b><span>qualified wallets</span></div><div><i className="round-icon chart"/><b>$437m</b><span>tracked value</span></div><div><i className="round-icon bolt"/><b>87</b><span>assets with signals</span></div></div></div><aside className="preview-card"><div className="preview-top"><div><h2>HYPE</h2><p>Signal score</p></div><span className="long-pill">● LONG</span><div className="preview-score"><strong>+0.33</strong><span>Medium confidence</span></div></div><div className="chart-box"><SparkPreview/></div><div className="preview-mini-grid"><div><small>Qualified wallets</small><b>50</b><svg viewBox="0 0 100 32"><path d="M4 24 L22 21 L36 25 L52 14 L66 20 L82 9 L96 11"/></svg></div><div><small>Tracked value</small><b>$437m</b><svg viewBox="0 0 100 32"><path d="M4 24 L18 23 L32 18 L48 22 L62 10 L78 14 L96 8"/></svg></div></div><div className="exposure-card"><small>Long vs short exposure</small><div className="big-split"><i style={{width:'68.3%'}}/><em style={{width:'31.7%'}}/></div><div><b>LONG 68.3%</b><strong>SHORT 31.7%</strong></div></div></aside></section><section className="feature-row"><article><i className="feature-icon users"/><span>01</span><h3>Qualified wallets</h3><p>Daily refreshed cohort using profitability, consistency, size, and anti-fluke scoring.</p><button>→</button></article><article><i className="feature-icon bars"/><span>02</span><h3>Value exposure</h3><p>See dollar-weighted long/short exposure, not just wallet counts.</p><button>→</button></article><article><i className="feature-icon clock"/><span>03</span><h3>Flow pressure</h3><p>Spot accumulation and distribution from recent position changes.</p><button>→</button></article></section><p className="risk-bar green-risk"><i>♢</i> Market intelligence only. Not financial advice. Crypto trading can result in loss.</p></main></>
}
