'use client'
import { useState } from 'react'
import Nav from '../../components/Nav'
import { getSupabase } from '../../lib/supabase'

export default function Login(){const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [msg,setMsg]=useState('')
async function signIn(){try{setMsg(''); const supabase=await getSupabase(); const { error }=await supabase.auth.signInWithPassword({email,password}); if(error)throw error; location.href='/dashboard'}catch(e:any){setMsg(e.message)}}
async function signUp(){try{setMsg(''); const supabase=await getSupabase(); const { error }=await supabase.auth.signUp({email,password}); if(error)throw error; setMsg('Account created. Check your email if confirmation is enabled, then log in.')}catch(e:any){setMsg(e.message)}}
return <><Nav/><main className="page-shell login-page"><section className="auth-shell"><div className="auth-copy"><p className="eyebrow">Members only</p><h1>Welcome back.</h1><p>Log in to view live smart-wallet signals, allocation targets, and market-flow pressure.</p><div className="auth-benefits"><div><i className="ico signal"/><b>Live signals</b><span>Real-time smart-wallet activity</span></div><div><i className="ico pie"/><b>Allocation targets</b><span>Track positioning bias and exposure</span></div><div><i className="ico flow"/><b>Market flow</b><span>See pressure before the crowd</span></div></div><p className="security">♢ Bank-level encryption. Your data stays private and secure.</p></div><div className="auth-card"><h2>Login</h2><p>Access your Copycat dashboard</p><label>Email<input className="input" placeholder="you@example.com" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input className="input" type="password" placeholder="Enter your password" value={password} onChange={e=>setPassword(e.target.value)}/></label><div className="form-row"><label className="check"><input type="checkbox"/> Remember me</label><a>Forgot password?</a></div><button className="btn full" onClick={signIn}>Login</button><button className="btn secondary full" onClick={signUp}>Create account</button><small className="secure-line">♢ Secure login protected by industry-standard encryption.</small>{msg&&<p className="form-msg">{msg}</p>}</div></section></main></>}
