'use client'
import { useEffect, useMemo, useState } from 'react'
import Nav from '../../components/Nav'
import { apiGet } from '../../lib/api'

function money(n:any){return '$'+Number(n||0).toLocaleString(undefined,{maximumFractionDigits:0})}
function compactMoney(n:any){const v=Math.abs(Number(n||0)); const sign=Number(n||0)<0?'-':''; if(v>=1_000_000_000)return sign+'$'+(v/1_000_000_000).toFixed(1)+'b'; if(v>=1_000_000)return sign+'$'+(v/1_000_000).toFixed(1)+'m'; if(v>=1_000)return sign+'$'+(v/1_000).toFixed(1)+'k'; return sign+'$'+v.toFixed(0)}
function pct(n:any){return (Number(n||0)*100).toFixed(1)+'%'}
function cls(n:any){return Number(n)>=0?'positive':'negative'}
function readFlow(n:any){return Number(n)>3?'Accumulation':Number(n)<-3?'Distribution':'Neutral'}
function fmtTime(ms:any){if(!ms)return 'Awaiting refresh'; const d=new Date(Number(ms)); return d.toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'})}
function ago(ms:any){if(!ms)return 'latest'; const diff=Math.max(0,Date.now()-Number(ms)); const mins=Math.round(diff/60000); if(mins<1)return 'just now'; if(mins<60)return `${mins}m ago`; const hrs=Math.round(mins/60); return `${hrs}h ago`}
function maskWallet(w:string){return w?`Wallet ${w.slice(0,4)}…${w.slice(-4)}`:'Wallet'}

const palette=['#35f1cf','#7c5cff','#36bdf5','#f59e0b','#22c55e','#f472b6','#a3e635','#fb7185']
const coinColors:Record<string,string>={HYPE:'#38f8d8',ETH:'#627eea',BTC:'#f7931a',SOL:'#14f195',ZEC:'#f4b728',NEAR:'#00ec97',MELANIA:'#d7a785',AAVE:'#6f7cff',TRX:'#ff4b4b',XRP:'#4b9fff',WLD:'#6b7280'}
function CoinIcon({coin}:{coin:string}){const c=coinColors[String(coin||'').toUpperCase()]||'#38f8d8'; const txt=String(coin||'?').slice(0,2).toUpperCase(); return <span className="coin-icon" style={{'--coin':c} as any}>{txt}</span>}
function Spark(){return <svg viewBox="0 0 92 32" className="mini-spark"><path d="M2 25 L15 22 L27 24 L39 14 L51 20 L62 9 L74 12 L90 7"/></svg>}

type Segment={coin:string; weight:number; color:string}
function polar(cx:number,cy:number,r:number,angle:number){const a=(angle-90)*Math.PI/180; return {x:cx+r*Math.cos(a), y:cy+r*Math.sin(a)}}
function donutPath(cx:number,cy:number,outer:number,inner:number,start:number,end:number){const s1=polar(cx,cy,outer,start), e1=polar(cx,cy,outer,end), s2=polar(cx,cy,inner,start), e2=polar(cx,cy,inner,end); const large=end-start>180?1:0; return `M ${s1.x} ${s1.y} A ${outer} ${outer} 0 ${large} 1 ${e1.x} ${e1.y} L ${e2.x} ${e2.y} A ${inner} ${inner} 0 ${large} 0 ${s2.x} ${s2.y} Z`}
function AllocationDonut({targets}:{targets:any[]}){const parts:Segment[]=useMemo(()=>{const clean=(targets||[]).filter(t=>Number(t.target_weight)>0).slice(0,6); const total=clean.reduce((a,t)=>a+Number(t.target_weight||0),0)||1; return clean.map((t,i)=>({coin:t.coin,weight:Number(t.target_weight||0)/total,color:palette[i%palette.length]}))},[targets]); let angle=0; if(!parts.length)return <div className="empty-chart">Targets will appear after the collector runs.</div>; return <div className="donut-wrap"><svg viewBox="0 0 220 220" className="donut" role="img" aria-label="Portfolio target allocation donut"><circle cx="110" cy="110" r="92" fill="rgba(0,0,0,.04)"/>{parts.map((p)=>{const start=angle; angle+=p.weight*360; return <path key={p.coin} d={donutPath(110,110,92,58,start,angle-.8)} fill={p.color} className="donut-seg"><title>{p.coin} {(p.weight*100).toFixed(1)}%</title></path>})}<circle cx="110" cy="110" r="52" className="donut-hole"/><text x="110" y="105" textAnchor="middle" className="donut-kicker">TARGETS</text><text x="110" y="130" textAnchor="middle" className="donut-number">{parts.length}</text></svg><div className="legend">{parts.map(p=><div className="legend-row" key={p.coin}><span style={{background:p.color}}/><b>{p.coin}</b><em>{(p.weight*100).toFixed(1)}%</em></div>)}</div></div>}
function ExposureBars({signals}:{signals:any[]}){const rows=(signals||[]).slice(0,8); const max=Math.max(1,...rows.map(r=>Number(r.value_long_usd||0)+Number(r.value_short_usd||0))); if(!rows.length)return <div className="empty-chart">Exposure bars will appear after the collector runs.</div>; return <div className="bars-list">{rows.map(r=>{const l=Number(r.value_long_usd||0), s=Number(r.value_short_usd||0); const lw=Math.max(2,(l/max)*100), sw=Math.max(2,(s/max)*100); return <div className="bar-row" key={r.coin}><div className="bar-label"><b>{r.coin}</b><span>{Number(r.signal).toFixed(2)}</span></div><div className="bar-track" title={`${r.coin}: long ${money(l)} / short ${money(s)}`}><i className="bar-long" style={{width:`${lw}%`}}/><i className="bar-short" style={{width:`${sw}%`}}/></div><div className="bar-values"><span>{compactMoney(l)}</span><span>{compactMoney(s)}</span></div></div>})}</div>}

export default function Dashboard(){
  const [summary,setSummary]=useState<any>({}); const [signals,setSignals]=useState<any[]>([]); const [targets,setTargets]=useState<any[]>([]); const [flow,setFlow]=useState<any[]>([]); const [orders,setOrders]=useState<any[]>([]); const [err,setErr]=useState('')
  async function load(){try{setErr(''); const [s,si,t,f,o]=await Promise.all([apiGet('/api/summary'),apiGet('/api/signals?limit=30'),apiGet('/api/targets'),apiGet('/api/flow?limit=30'),apiGet('/api/recent-orders?limit=3').catch(()=>[])]); setSummary(s); setSignals(si); setTargets(t); setFlow(f); setOrders(o)}catch(e:any){setErr(e.message)}}
  useEffect(()=>{load(); const id=setInterval(load,30000); return()=>clearInterval(id)},[])
  const longValue=signals.reduce((a,r)=>a+Number(r.value_long_usd||0),0); const shortValue=signals.reduce((a,r)=>a+Number(r.value_short_usd||0),0); const isLong=longValue>=shortValue
  const orderRows=(orders.length?orders:flow.slice(0,3).map(r=>({coin:r.coin, side:Number(r.net_value_flow_usd)>=0?'Long':'Short', wallet_label:'Top wallet', ts_ms:summary.latest_signal_ts_ms, delta_value_usd:r.net_value_flow_usd})))
  return <><Nav/><main className="page-shell dashboard-page"><section className="dash-top"><div><p className="eyebrow live-dot">Live smart-wallet tape</p><h1>Market intelligence.<br/><em>Follow the best.</em></h1><p>Value-weighted positioning from qualified Hyperliquid wallets. Built to show what serious traders are leaning into.</p></div><div className="bias-wrap"><span>Positioning bias</span><button className={`bias-toggle ${isLong?'is-long':'is-short'}`}><i/><b>{isLong?'LONG':'SHORT'}</b></button></div><aside className="orders-card"><h3>Most recent orders</h3>{orderRows.map((o:any,i:number)=><div className="order-row" key={`${o.coin}-${i}`}><CoinIcon coin={o.coin}/><b>{o.coin}</b><span className={String(o.side).toLowerCase().includes('short')||String(o.side).toLowerCase().includes('reduce')?'negative':'positive'}>{o.side}</span><em>{o.wallet_label || maskWallet(o.wallet)}</em><small>{ago(o.ts_ms)}</small></div>)}<button className="ghost-action small">View all orders →</button></aside></section>{err&&<p className="notice gold">{err}</p>}

<section className="metric-grid dashboard-metrics"><div className="metric-card"><i className="ico users"/><small>Qualified wallets</small><b>{summary.qualified_wallets||0}</b><span>ranked daily</span><Spark/></div><div className="metric-card"><i className="ico wallet"/><small>Tracked account value</small><b>{money(summary.tracked_account_value_usd)}</b><span>latest snapshots</span><Spark/></div><div className="metric-card"><i className="ico chart"/><small>Open position value</small><b>{money(summary.tracked_open_position_value_usd)}</b><span>{summary.open_positions||0} live positions</span><Spark/></div><div className="metric-card"><i className="ico bolt"/><small>Assets with signals</small><b>{summary.assets_with_signals||0}</b><span>cross-asset breadth</span><Spark/></div><div className="metric-card refresh"><i className="ico clock"/><small>Signal refresh</small><b>{fmtTime(summary.latest_signal_ts_ms)}</b><span>UTC</span></div></section>

<section className="dash-charts"><div className="chart-card"><div className="section-head"><div><p className="eyebrow">Portfolio allocation</p></div></div><AllocationDonut targets={targets}/></div><div className="chart-card"><div className="section-head"><div><p className="eyebrow">Long vs short exposure</p></div><div className="bar-key"><span className="key-long">Long</span><span className="key-short">Short</span></div></div><ExposureBars signals={signals}/></div></section>

<section className="dash-tables"><div className="table-card"><div className="section-head"><div><p className="eyebrow">Asset signal board</p></div><span className="hint">value-weighted, not wallet-count only</span></div><table><thead><tr><th>#</th><th>Asset</th><th>Signal</th><th>Confidence</th><th>Wallets</th><th>Value L/S</th><th>Net value</th><th>% total value</th></tr></thead><tbody>{signals.slice(0,8).map((r,i)=><tr key={r.coin}><td>{i+1}</td><td><span className="asset-cell"><CoinIcon coin={r.coin}/><b>{r.coin}</b></span></td><td className={cls(r.signal)}>{Number(r.signal).toFixed(2)}</td><td><span className={`pill ${r.confidence==='High'?'conf-high':r.confidence==='Medium'?'conf-medium':''}`}>{r.confidence}</span></td><td>{r.wallets_long} long / {r.wallets_short} short</td><td>{money(r.value_long_usd)} / {money(r.value_short_usd)}</td><td className={cls(r.net_value_usd)}>{money(r.net_value_usd)}</td><td>{pct(r.value_long_pct_total)} long / {pct(r.value_short_pct_total)} short</td></tr>)}</tbody></table><a className="table-link">View full signal board →</a></div><div className="table-card"><div className="section-head"><div><p className="eyebrow">Recent buyer / seller pressure</p></div><span className="hint">largest flow changes first</span></div><table><thead><tr><th>Asset</th><th>Net buyers</th><th>Bullish flow</th><th>Bearish flow</th><th>Net value flow</th><th>Read</th></tr></thead><tbody>{flow.slice(0,6).map(r=><tr key={r.coin}><td><span className="asset-cell"><CoinIcon coin={r.coin}/><b>{r.coin}</b></span></td><td className={cls(r.net_buyer_count)}>{r.net_buyer_count}</td><td>{money(r.bullish_value_flow_usd)}</td><td>{money(r.bearish_value_flow_usd)}</td><td className={cls(r.net_value_flow_usd)}>{money(r.net_value_flow_usd)}</td><td><span className={`pill read-${readFlow(r.net_buyer_count).toLowerCase()}`}>{readFlow(r.net_buyer_count)}</span></td></tr>)}</tbody></table><a className="table-link">View full pressure tape →</a></div></section><p className="notice dashboard-notice"><span>♢</span> Market intelligence only. Not financial advice. Crypto trading can result in loss. <em>● Data updates every 30s</em></p></main></>}
